name: HairCare
options:
  bundleIdPrefix: br.com.haircare
  minimumXcodeGenVersion: 2.44.1
  createIntermediateGroups: true

fileGroups:
  - TestPlan.xctestplan

configs:
  debug: debug
  release: release

settingGroups:
  SwiftConcurrency:
    SWIFT_APPROACHABLE_CONCURRENCY: NO
    SWIFT_DEFAULT_ACTOR_ISOLATION: nonisolated
    SWIFT_STRICT_CONCURRENCY: complete
  Localization:
    STRING_CATALOG_GENERATE_SYMBOLS: Yes
    LOCALIZATION_PREFERS_STRING_CATALOGS: Yes
  AssetCatalogCompiler:
    ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: Yes
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: Yes

settings:
  APP_NAME: "Hair Care"
  groups: [SwiftConcurrency, Localization]
  base:
    TARGETED_DEVICE_FAMILY: 1
    IPHONEOS_DEPLOYMENT_TARGET: "17.6"
    
targetTemplates:
  AppTemplate:
    platform: iOS
    deploymentTarget: "17.6"

  AppTestsTemplate:
    dependencies:
      - target: App
    settings:
      GENERATE_INFOPLIST_FILE: YES

targets:
  App:
    templates: 
      - AppTemplate
    type: application
    sources: [HairCare]
    settings:
      groups: [AssetCatalogCompiler]
      configs:
        debug:
          DEBUG_MODE: YES
          PRODUCT_BUNDLE_IDENTIFIER: br.com.haircare.debug.App
          PRODUCT_DISPLAY_NAME: "Debug $(APP_NAME)"
        release:
          DEBUG_MODE: NO
          PRODUCT_BUNDLE_IDENTIFIER: br.com.haircare.App
          PRODUCT_DISPLAY_NAME: $(APP_NAME)
    preBuildScripts:
      - name: Check for duplicated strings
        shell: /bin/sh
        script: |
          if which python3 >/dev/null; then
            python3 "${SRCROOT}/scripts/check_duplicated_strings.py" "${SRCROOT}"
          else
            echo "warning: Python 3 não encontrado para validar .xcstrings"
          fi

  AppTests:
    templates:
      - AppTemplate
      - AppTestsTemplate
    type: bundle.unit-test
    sources: [HairCareTests]

  AppUITests:
    templates: 
      - AppTemplate
      - AppTestsTemplate
    type: bundle.ui-testing
    sources: [HairCareUITests]

schemes:
  App:
    build:
      targets:
        App: all
    run:
      config: debug
    test:
      config: debug
      gatherCoverageData: true
      coverageTargets: 
        - App

      targets:
        - name: AppTests
        - name: AppUITests

      testPlans:
        - path: TestPlan.xctestplan
          defaultPlan: true
    profile:
      config: release
    analyze:
      config: debug
    archive:
      config: release

