//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 4 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var homePage: homePage { .init(source: .init(bundle: bundle, tableName: "HomePage", preferredLanguages: preferredLanguages, locale: locale)) }
    var productDetail: productDetail { .init(source: .init(bundle: bundle, tableName: "ProductDetail", preferredLanguages: preferredLanguages, locale: locale)) }
    var startPage: startPage { .init(source: .init(bundle: bundle, tableName: "StartPage", preferredLanguages: preferredLanguages, locale: locale)) }
    var storeItemCategory: storeItemCategory { .init(source: .init(bundle: bundle, tableName: "StoreItemCategory", preferredLanguages: preferredLanguages, locale: locale)) }

    func homePage(preferredLanguages: [String]) -> homePage {
      .init(source: .init(bundle: bundle, tableName: "HomePage", preferredLanguages: preferredLanguages, locale: locale))
    }
    func productDetail(preferredLanguages: [String]) -> productDetail {
      .init(source: .init(bundle: bundle, tableName: "ProductDetail", preferredLanguages: preferredLanguages, locale: locale))
    }
    func startPage(preferredLanguages: [String]) -> startPage {
      .init(source: .init(bundle: bundle, tableName: "StartPage", preferredLanguages: preferredLanguages, locale: locale))
    }
    func storeItemCategory(preferredLanguages: [String]) -> storeItemCategory {
      .init(source: .init(bundle: bundle, tableName: "StoreItemCategory", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.homePage` struct is generated, and contains static references to 1 localization keys.
    struct homePage {
      let source: RswiftResources.StringResource.Source

      /// en translation: New collection
      ///
      /// Key: new_collection
      ///
      /// Locales: en, pt-BR
      var new_collection: RswiftResources.StringResource { .init(key: "new_collection", tableName: "HomePage", source: source, developmentValue: "New collection", comment: nil) }
    }

    /// This `_R.string.productDetail` struct is generated, and contains static references to 5 localization keys.
    struct productDetail {
      let source: RswiftResources.StringResource.Source

      /// en translation: Add to cart
      ///
      /// Key: add_to_cart
      ///
      /// Locales: en, pt-BR
      var add_to_cart: RswiftResources.StringResource { .init(key: "add_to_cart", tableName: "ProductDetail", source: source, developmentValue: "Add to cart", comment: nil) }

      /// en translation: Description
      ///
      /// Key: description
      ///
      /// Locales: en, pt-BR
      var description: RswiftResources.StringResource { .init(key: "description", tableName: "ProductDetail", source: source, developmentValue: "Description", comment: nil) }

      /// en translation: Details
      ///
      /// Key: details
      ///
      /// Locales: en, pt-BR
      var details: RswiftResources.StringResource { .init(key: "details", tableName: "ProductDetail", source: source, developmentValue: "Details", comment: nil) }

      /// en translation: Ingredients
      ///
      /// Key: ingredients
      ///
      /// Locales: en, pt-BR
      var ingredients: RswiftResources.StringResource { .init(key: "ingredients", tableName: "ProductDetail", source: source, developmentValue: "Ingredients", comment: nil) }

      /// en translation: Read more
      ///
      /// Key: read_more
      ///
      /// Locales: en, pt-BR
      var read_more: RswiftResources.StringResource { .init(key: "read_more", tableName: "ProductDetail", source: source, developmentValue: "Read more", comment: nil) }
    }

    /// This `_R.string.startPage` struct is generated, and contains static references to 1 localization keys.
    struct startPage {
      let source: RswiftResources.StringResource.Source

      /// en translation: Get Started
      ///
      /// Key: get_started
      ///
      /// Locales: en, pt-BR
      var get_started: RswiftResources.StringResource { .init(key: "get_started", tableName: "StartPage", source: source, developmentValue: "Get Started", comment: nil) }
    }

    /// This `_R.string.storeItemCategory` struct is generated, and contains static references to 5 localization keys.
    struct storeItemCategory {
      let source: RswiftResources.StringResource.Source

      /// en translation: Conditioner
      ///
      /// Key: conditioner
      ///
      /// Locales: en, pt-BR
      var conditioner: RswiftResources.StringResource { .init(key: "conditioner", tableName: "StoreItemCategory", source: source, developmentValue: "Conditioner", comment: nil) }

      /// en translation: Hair mask
      ///
      /// Key: hair_mask
      ///
      /// Locales: en, pt-BR
      var hair_mask: RswiftResources.StringResource { .init(key: "hair_mask", tableName: "StoreItemCategory", source: source, developmentValue: "Hair mask", comment: nil) }

      /// en translation: Packs
      ///
      /// Key: packs
      ///
      /// Locales: en, pt-BR
      var packs: RswiftResources.StringResource { .init(key: "packs", tableName: "StoreItemCategory", source: source, developmentValue: "Packs", comment: nil) }

      /// en translation: Painting
      ///
      /// Key: painting
      ///
      /// Locales: en, pt-BR
      var painting: RswiftResources.StringResource { .init(key: "painting", tableName: "StoreItemCategory", source: source, developmentValue: "Painting", comment: nil) }

      /// en translation: Shampoo
      ///
      /// Key: shampoo
      ///
      /// Locales: en, pt-BR
      var shampoo: RswiftResources.StringResource { .init(key: "shampoo", tableName: "StoreItemCategory", source: source, developmentValue: "Shampoo", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 3 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `AsyncImagePlaceholder`.
    var asyncImagePlaceholder: RswiftResources.ColorResource { .init(name: "AsyncImagePlaceholder", path: [], bundle: bundle) }

    /// Color `CardBackground`.
    var cardBackground: RswiftResources.ColorResource { .init(name: "CardBackground", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 3 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `SampleProduct`.
    var sampleProduct: RswiftResources.ImageResource { .init(name: "SampleProduct", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `SampleProduct2`.
    var sampleProduct2: RswiftResources.ImageResource { .init(name: "SampleProduct2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `StartPageBackground`.
    var startPageBackground: RswiftResources.ImageResource { .init(name: "StartPageBackground", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `productsByCategory.json`.
    var productsByCategoryJson: RswiftResources.FileResource { .init(name: "productsByCategory", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }
}